#!/bin/sh

INSTALL_DIR="/var/packages/FBS/target"
DATA_DIR="/volume1/FBS"

preinst() {
    # Maak data directory aan als die nog niet bestaat
    mkdir -p "${DATA_DIR}"
    exit 0
}

postinst() {
    # Symlink de database locatie naar de data directory
    ln -sf "${DATA_DIR}/fbs.db" "${INSTALL_DIR}/app/fbs.db"
    # Zet correcte permissies
    chown -R root:root "${INSTALL_DIR}"
    chmod -R 755 "${INSTALL_DIR}"
    exit 0
}

preuninst() {
    exit 0
}

postuninst() {
    exit 0
}

preupgrade() {
    exit 0
}

postupgrade() {
    # Herstel symlink na upgrade
    ln -sf "${DATA_DIR}/fbs.db" "${INSTALL_DIR}/app/fbs.db"
    exit 0
}

case $1 in
    pre-install)   preinst   ;;
    post-install)  postinst  ;;
    pre-uninstall) preuninst ;;
    post-uninstall) postuninst ;;
    pre-upgrade)   preupgrade ;;
    post-upgrade)  postupgrade ;;
esac
